# Generated by Django 3.1.5 on 2021-01-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='image')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_created')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='date_updated')),
            ],
        ),
    ]
